// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, name, locale, settings, created_at, updated_at, auto_resolve_duration, custom_attributes, domain, feature_flags, feature_flags_ext_1, internal_attributes, limits, status, support_email FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Locale,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoResolveDuration,
		&i.CustomAttributes,
		&i.Domain,
		&i.FeatureFlags,
		&i.FeatureFlagsExt1,
		&i.InternalAttributes,
		&i.Limits,
		&i.Status,
		&i.SupportEmail,
	)
	return i, err
}
