// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*) FROM companies
WHERE account_id = $1 AND ($2::text = '' OR name ILIKE '%' || $2::text || '%' OR domain ILIKE '%' || $2::text || '%')
`

type CountCompaniesParams struct {
	AccountID int64
	Search    string
}

func (q *Queries) CountCompanies(ctx context.Context, arg CountCompaniesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies, arg.AccountID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (account_id, name, domain, description, additional_attributes, custom_attributes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, name, domain, description, additional_attributes, account_id, created_at, updated_at, custom_attributes, contacts_count, last_activity_at
`

type CreateCompanyParams struct {
	AccountID            int64
	Name                 string
	Domain               pgtype.Text
	Description          pgtype.Text
	AdditionalAttributes []byte
	CustomAttributes     []byte
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.AccountID,
		arg.Name,
		arg.Domain,
		arg.Description,
		arg.AdditionalAttributes,
		arg.CustomAttributes,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Description,
		&i.AdditionalAttributes,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomAttributes,
		&i.ContactsCount,
		&i.LastActivityAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, domain, description, additional_attributes, account_id, created_at, updated_at, custom_attributes, contacts_count, last_activity_at FROM companies WHERE account_id = $1 AND id = $2
`

type GetCompanyParams struct {
	AccountID int64
	ID        int64
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.AccountID, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Description,
		&i.AdditionalAttributes,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomAttributes,
		&i.ContactsCount,
		&i.LastActivityAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, domain, description, additional_attributes, account_id, created_at, updated_at, custom_attributes, contacts_count, last_activity_at FROM companies
WHERE account_id = $1 AND ($2::text = '' OR name ILIKE '%' || $2::text || '%' OR domain ILIKE '%' || $2::text || '%')
ORDER BY
 CASE WHEN $3::text = 'name' THEN name END ASC,
 CASE WHEN $3::text = '-name' THEN name END DESC,
 CASE WHEN $3::text = 'domain' THEN domain END ASC,
 CASE WHEN $3::text = '-domain' THEN domain END DESC,
 CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
 CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
 CASE WHEN $3::text = 'last_activity_at' THEN last_activity_at END ASC NULLS LAST,
 CASE WHEN $3::text = '-last_activity_at' THEN last_activity_at END DESC NULLS LAST,
 CASE WHEN $3::text = 'contacts_count' THEN contacts_count END ASC NULLS LAST,
 CASE WHEN $3::text = '-contacts_count' THEN contacts_count END DESC NULLS LAST,
 id ASC
LIMIT $5 OFFSET $4
`

type ListCompaniesParams struct {
	AccountID  int64
	Search     string
	Sort       string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies,
		arg.AccountID,
		arg.Search,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Description,
			&i.AdditionalAttributes,
			&i.AccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomAttributes,
			&i.ContactsCount,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
