// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_filters.sql

package sqlc

import (
	"context"
)

const countCustomFiltersOfUser = `-- name: CountCustomFiltersOfUser :one
SELECT count(*) FROM custom_filters WHERE account_id = $1 AND user_id = $2
`

type CountCustomFiltersOfUserParams struct {
	AccountID int64
	UserID    int64
}

func (q *Queries) CountCustomFiltersOfUser(ctx context.Context, arg CountCustomFiltersOfUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomFiltersOfUser, arg.AccountID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomFilter = `-- name: CreateCustomFilter :one
INSERT INTO custom_filters (account_id, user_id, name, filter_type, query, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, name, filter_type, query, account_id, user_id, created_at, updated_at
`

type CreateCustomFilterParams struct {
	AccountID  int64
	UserID     int64
	Name       string
	FilterType int32
	Query      []byte
}

func (q *Queries) CreateCustomFilter(ctx context.Context, arg CreateCustomFilterParams) (CustomFilter, error) {
	row := q.db.QueryRow(ctx, createCustomFilter,
		arg.AccountID,
		arg.UserID,
		arg.Name,
		arg.FilterType,
		arg.Query,
	)
	var i CustomFilter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterType,
		&i.Query,
		&i.AccountID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomFilter = `-- name: DeleteCustomFilter :execrows
DELETE FROM custom_filters WHERE account_id = $1 AND user_id = $2 AND id = $3
`

type DeleteCustomFilterParams struct {
	AccountID int64
	UserID    int64
	ID        int64
}

func (q *Queries) DeleteCustomFilter(ctx context.Context, arg DeleteCustomFilterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomFilter, arg.AccountID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomFilter = `-- name: GetCustomFilter :one
SELECT id, name, filter_type, query, account_id, user_id, created_at, updated_at FROM custom_filters
WHERE account_id = $1 AND user_id = $2 AND id = $3
`

type GetCustomFilterParams struct {
	AccountID int64
	UserID    int64
	ID        int64
}

func (q *Queries) GetCustomFilter(ctx context.Context, arg GetCustomFilterParams) (CustomFilter, error) {
	row := q.db.QueryRow(ctx, getCustomFilter, arg.AccountID, arg.UserID, arg.ID)
	var i CustomFilter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterType,
		&i.Query,
		&i.AccountID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomFilters = `-- name: ListCustomFilters :many
SELECT id, name, filter_type, query, account_id, user_id, created_at, updated_at FROM custom_filters
WHERE account_id = $1 AND user_id = $2 AND filter_type = $3 ORDER BY id
`

type ListCustomFiltersParams struct {
	AccountID  int64
	UserID     int64
	FilterType int32
}

func (q *Queries) ListCustomFilters(ctx context.Context, arg ListCustomFiltersParams) ([]CustomFilter, error) {
	rows, err := q.db.Query(ctx, listCustomFilters, arg.AccountID, arg.UserID, arg.FilterType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFilter{}
	for rows.Next() {
		var i CustomFilter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilterType,
			&i.Query,
			&i.AccountID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFilter = `-- name: UpdateCustomFilter :one
UPDATE custom_filters SET name = $4, filter_type = $5, query = $6, updated_at = now()
WHERE account_id = $1 AND user_id = $2 AND id = $3
RETURNING id, name, filter_type, query, account_id, user_id, created_at, updated_at
`

type UpdateCustomFilterParams struct {
	AccountID  int64
	UserID     int64
	ID         int64
	Name       string
	FilterType int32
	Query      []byte
}

func (q *Queries) UpdateCustomFilter(ctx context.Context, arg UpdateCustomFilterParams) (CustomFilter, error) {
	row := q.db.QueryRow(ctx, updateCustomFilter,
		arg.AccountID,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.FilterType,
		arg.Query,
	)
	var i CustomFilter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterType,
		&i.Query,
		&i.AccountID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
