// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inboxes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listInboxes = `-- name: ListInboxes :many
SELECT i.id, i.channel_id, i.name, i.channel_type, i.greeting_enabled, i.greeting_message, i.working_hours_enabled,
       i.enable_email_collect, i.csat_survey_enabled, i.csat_config, i.enable_auto_assignment, i.auto_assignment_config,
       i.out_of_office_message, i.timezone, i.allow_messages_after_resolved, i.lock_to_single_conversation,
       i.sender_name_type, i.business_name,
       tg.bot_name, wa.phone_number, wa.provider, wa.message_templates,
       COALESCE((SELECT jsonb_agg(jsonb_build_object(
                   'day_of_week', wh.day_of_week, 'closed_all_day', wh.closed_all_day,
                   'open_hour', wh.open_hour, 'open_minutes', wh.open_minutes,
                   'close_hour', wh.close_hour, 'close_minutes', wh.close_minutes,
                   'open_all_day', wh.open_all_day) ORDER BY wh.day_of_week)
                 FROM working_hours wh WHERE wh.inbox_id = i.id), '[]')::jsonb AS working_hours
FROM inboxes i
LEFT JOIN channel_telegram tg ON i.channel_type = 'Channel::Telegram' AND tg.id = i.channel_id
LEFT JOIN channel_whatsapp wa ON i.channel_type = 'Channel::Whatsapp' AND wa.id = i.channel_id
WHERE i.account_id = $1
  AND ($2::int IS NULL
       OR i.id IN (SELECT im.inbox_id FROM inbox_members im WHERE im.user_id = $2::int))
ORDER BY lower(i.name)
`

type ListInboxesParams struct {
	AccountID int32
	MemberID  pgtype.Int4
}

type ListInboxesRow struct {
	ID                         int32
	ChannelID                  int32
	Name                       string
	ChannelType                pgtype.Text
	GreetingEnabled            pgtype.Bool
	GreetingMessage            pgtype.Text
	WorkingHoursEnabled        pgtype.Bool
	EnableEmailCollect         pgtype.Bool
	CsatSurveyEnabled          pgtype.Bool
	CsatConfig                 []byte
	EnableAutoAssignment       pgtype.Bool
	AutoAssignmentConfig       []byte
	OutOfOfficeMessage         pgtype.Text
	Timezone                   pgtype.Text
	AllowMessagesAfterResolved pgtype.Bool
	LockToSingleConversation   bool
	SenderNameType             int32
	BusinessName               pgtype.Text
	BotName                    pgtype.Text
	PhoneNumber                pgtype.Text
	Provider                   pgtype.Text
	MessageTemplates           []byte
	WorkingHours               []byte
}

// InboxesController#index: policy_scope (admin vê todas; agente só as de inbox_members) + order_by_name.
// Só colunas públicas do canal: tokens e provider_config nunca saem daqui (ficam em models.InboxConfigs).
func (q *Queries) ListInboxes(ctx context.Context, arg ListInboxesParams) ([]ListInboxesRow, error) {
	rows, err := q.db.Query(ctx, listInboxes, arg.AccountID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxesRow{}
	for rows.Next() {
		var i ListInboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.ChannelType,
			&i.GreetingEnabled,
			&i.GreetingMessage,
			&i.WorkingHoursEnabled,
			&i.EnableEmailCollect,
			&i.CsatSurveyEnabled,
			&i.CsatConfig,
			&i.EnableAutoAssignment,
			&i.AutoAssignmentConfig,
			&i.OutOfOfficeMessage,
			&i.Timezone,
			&i.AllowMessagesAfterResolved,
			&i.LockToSingleConversation,
			&i.SenderNameType,
			&i.BusinessName,
			&i.BotName,
			&i.PhoneNumber,
			&i.Provider,
			&i.MessageTemplates,
			&i.WorkingHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
