// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_configs.sql

package sqlc

import (
	"context"
)

const getInboxConfig = `-- name: GetInboxConfig :one
SELECT inbox_id, provider_config FROM chatwooter_inbox_configs WHERE inbox_id = $1
`

func (q *Queries) GetInboxConfig(ctx context.Context, inboxID int32) (ChatwooterInboxConfig, error) {
	row := q.db.QueryRow(ctx, getInboxConfig, inboxID)
	var i ChatwooterInboxConfig
	err := row.Scan(&i.InboxID, &i.ProviderConfig)
	return i, err
}

const listInboxConfigs = `-- name: ListInboxConfigs :many
SELECT inbox_id, provider_config FROM chatwooter_inbox_configs ORDER BY inbox_id
`

func (q *Queries) ListInboxConfigs(ctx context.Context) ([]ChatwooterInboxConfig, error) {
	rows, err := q.db.Query(ctx, listInboxConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatwooterInboxConfig{}
	for rows.Next() {
		var i ChatwooterInboxConfig
		if err := rows.Scan(&i.InboxID, &i.ProviderConfig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInboxConfig = `-- name: UpsertInboxConfig :exec
INSERT INTO chatwooter_inbox_configs (inbox_id, provider_config) VALUES ($1, $2)
ON CONFLICT (inbox_id) DO UPDATE SET provider_config = EXCLUDED.provider_config
`

type UpsertInboxConfigParams struct {
	InboxID        int32
	ProviderConfig []byte
}

func (q *Queries) UpsertInboxConfig(ctx context.Context, arg UpsertInboxConfigParams) error {
	_, err := q.db.Exec(ctx, upsertInboxConfig, arg.InboxID, arg.ProviderConfig)
	return err
}
