// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLabels = `-- name: ListLabels :many
SELECT id, title, description, color, show_on_sidebar FROM labels WHERE account_id = $1 ORDER BY title
`

type ListLabelsRow struct {
	ID            int64
	Title         pgtype.Text
	Description   pgtype.Text
	Color         string
	ShowOnSidebar pgtype.Bool
}

// Label tem default_scope order(:title) no Chatwoot.
func (q *Queries) ListLabels(ctx context.Context, accountID pgtype.Int8) ([]ListLabelsRow, error) {
	rows, err := q.db.Query(ctx, listLabels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsRow{}
	for rows.Next() {
		var i ListLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Color,
			&i.ShowOnSidebar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
