// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        int64
	OwnerType pgtype.Text
	OwnerID   pgtype.Int8
	Token     pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Account struct {
	ID                  int32
	Name                string
	Locale              pgtype.Int4
	Settings            []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AutoResolveDuration pgtype.Int4
	CustomAttributes    []byte
	Domain              pgtype.Text
	FeatureFlags        int64
	FeatureFlagsExt1    int64
	InternalAttributes  []byte
	Limits              []byte
	Status              pgtype.Int4
	SupportEmail        pgtype.Text
}

type AccountSamlSetting struct {
	ID           int64
	AccountID    int64
	SsoUrl       pgtype.Text
	Certificate  pgtype.Text
	SpEntityID   pgtype.Text
	IdpEntityID  pgtype.Text
	RoleMappings []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AccountUser struct {
	ID                    int64
	AccountID             pgtype.Int8
	UserID                pgtype.Int8
	Role                  pgtype.Int4
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Availability          int32
	AutoOffline           bool
	ActiveAt              *time.Time
	AgentCapacityPolicyID pgtype.Int8
	CustomRoleID          pgtype.Int8
	InviterID             pgtype.Int8
}

type ActionMailboxInboundEmail struct {
	ID              int64
	Status          int32
	MessageID       string
	MessageChecksum string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ActiveStorageAttachment struct {
	ID         int64
	Name       string
	RecordType string
	RecordID   int64
	BlobID     int64
	CreatedAt  time.Time
}

type ActiveStorageBlob struct {
	ID          int64
	Key         string
	Filename    string
	ContentType pgtype.Text
	Metadata    pgtype.Text
	ByteSize    int64
	Checksum    pgtype.Text
	CreatedAt   time.Time
	ServiceName string
}

type ActiveStorageVariantRecord struct {
	ID              int64
	BlobID          int64
	VariationDigest string
}

type AgentBot struct {
	ID          int64
	Name        pgtype.Text
	Description pgtype.Text
	OutgoingUrl pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AccountID   pgtype.Int8
	BotType     pgtype.Int4
	BotConfig   []byte
	Secret      pgtype.Text
}

type AgentBotInbox struct {
	ID         int64
	InboxID    pgtype.Int4
	AgentBotID pgtype.Int4
	Status     pgtype.Int4
	CreatedAt  time.Time
	UpdatedAt  time.Time
	AccountID  pgtype.Int4
}

type AgentCapacityPolicy struct {
	ID             int64
	AccountID      int64
	Name           string
	Description    pgtype.Text
	ExclusionRules []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AgentSession struct {
	ID               int64
	SessionType      int32
	SubjectType      string
	SubjectID        int64
	ResultType       pgtype.Text
	ResultID         pgtype.Int8
	AccountID        int64
	AssistantID      int64
	UserID           pgtype.Int8
	LlmModel         pgtype.Text
	CreditsConsumed  pgtype.Float8
	FaqIds           []byte
	DocumentIds      []byte
	ScenarioIds      []byte
	RunContext       []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CitedDocumentIds []byte
	UsedFaqIds       []byte
}

type AppliedSla struct {
	ID             int64
	AccountID      int64
	SlaPolicyID    int64
	ConversationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SlaStatus      pgtype.Int4
	CompletedAt    *time.Time
}

type Article struct {
	ID                  int64
	AccountID           int32
	PortalID            int32
	CategoryID          pgtype.Int4
	FolderID            pgtype.Int4
	Title               pgtype.Text
	Description         pgtype.Text
	Content             pgtype.Text
	Status              pgtype.Int4
	Views               pgtype.Int4
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AuthorID            pgtype.Int8
	AssociatedArticleID pgtype.Int8
	Meta                []byte
	Slug                string
	Position            pgtype.Int4
	Locale              string
	DraftTitle          pgtype.Text
	DraftContent        pgtype.Text
}

type ArticleEmbedding struct {
	ID        int64
	ArticleID int64
	Term      string
	Embedding interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AssignmentPolicy struct {
	ID                     int64
	AccountID              int64
	Name                   string
	Description            pgtype.Text
	AssignmentOrder        int32
	ConversationPriority   int32
	FairDistributionLimit  int32
	FairDistributionWindow int32
	Enabled                bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ExcludeOlderThanHours  pgtype.Int4
}

type Attachment struct {
	ID              int32
	MessageID       int32
	FileType        pgtype.Int4
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AccountID       int32
	CoordinatesLat  pgtype.Float8
	CoordinatesLong pgtype.Float8
	Extension       pgtype.Text
	ExternalUrl     pgtype.Text
	FallbackTitle   pgtype.Text
	Meta            []byte
}

type Audit struct {
	ID             int64
	AuditableID    pgtype.Int8
	AuditableType  pgtype.Text
	AssociatedID   pgtype.Int8
	AssociatedType pgtype.Text
	UserID         pgtype.Int8
	UserType       pgtype.Text
	Username       pgtype.Text
	Action         pgtype.Text
	AuditedChanges []byte
	Version        pgtype.Int4
	Comment        pgtype.Text
	RemoteAddress  pgtype.Text
	RequestUuid    pgtype.Text
	CreatedAt      *time.Time
	City           pgtype.Text
	Country        pgtype.Text
	CountryCode    pgtype.Text
}

type AutomationRule struct {
	ID             int64
	AccountID      int64
	Name           string
	Description    pgtype.Text
	EventName      string
	Conditions     []byte
	Actions        []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Active         bool
	ExecutionDelay pgtype.Int4
}

type AutomationRulePendingExecution struct {
	ID               int64
	AutomationRuleID int64
	ConversationID   int64
	AccountID        int64
	MessageID        pgtype.Int8
	DueAt            time.Time
	EpisodeKey       string
	Status           int32
	SkipReason       pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Call struct {
	ID                int64
	AccountID         int64
	InboxID           int64
	ConversationID    int64
	ContactID         int64
	MessageID         pgtype.Int8
	AcceptedByAgentID pgtype.Int8
	ProviderCallID    string
	Provider          int32
	Direction         int32
	Status            string
	StartedAt         *time.Time
	DurationSeconds   pgtype.Int4
	EndReason         pgtype.Text
	Meta              []byte
	Transcript        pgtype.Text
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Campaign struct {
	ID                             int64
	DisplayID                      int32
	Title                          string
	Description                    pgtype.Text
	Message                        string
	SenderID                       pgtype.Int4
	Enabled                        pgtype.Bool
	AccountID                      int64
	InboxID                        int64
	TriggerRules                   []byte
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
	CampaignType                   int32
	CampaignStatus                 int32
	Audience                       []byte
	ScheduledAt                    *time.Time
	TriggerOnlyDuringBusinessHours pgtype.Bool
	TemplateParams                 []byte
	StartedAt                      *time.Time
	CompletedAt                    *time.Time
}

type CampaignRecipient struct {
	ID             int64
	AccountID      int64
	CampaignID     int64
	ContactID      int64
	InboxID        int64
	SourceID       pgtype.Text
	Status         int32
	ErrorCode      pgtype.Text
	ErrorTitle     pgtype.Text
	ErrorMessage   pgtype.Text
	MessageContent pgtype.Text
	SentAt         *time.Time
	DeliveredAt    *time.Time
	ReadAt         *time.Time
	FailedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CannedResponse struct {
	ID        int32
	AccountID int32
	ShortCode pgtype.Text
	Content   pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CaptainAssistant struct {
	ID                 int64
	Name               string
	AccountID          int64
	Description        pgtype.Text
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Config             []byte
	ResponseGuidelines []byte
	Guardrails         []byte
}

type CaptainAssistantResponse struct {
	ID               int64
	Question         string
	Answer           string
	Embedding        interface{}
	AssistantID      int64
	DocumentableID   pgtype.Int8
	AccountID        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Status           int32
	DocumentableType pgtype.Text
	Edited           bool
}

type CaptainCustomTool struct {
	ID               int64
	AccountID        int64
	Slug             string
	Title            string
	Description      pgtype.Text
	HttpMethod       string
	EndpointUrl      string
	RequestTemplate  pgtype.Text
	ResponseTemplate pgtype.Text
	AuthType         pgtype.Text
	AuthConfig       []byte
	ParamSchema      []byte
	Enabled          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	AssistantID      pgtype.Int8
}

type CaptainDocument struct {
	ID                  int64
	Name                pgtype.Text
	ExternalLink        string
	Content             pgtype.Text
	AssistantID         int64
	AccountID           int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Status              int32
	Metadata            []byte
	SyncStatus          pgtype.Int4
	LastSyncedAt        *time.Time
	LastSyncAttemptedAt *time.Time
}

type CaptainFaqObservation struct {
	ID                int64
	AccountID         int64
	ConversationID    int64
	FaqSuggestionID   pgtype.Int8
	GeneratedQuestion string
	GeneratedAnswer   string
	Language          string
	Status            int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CaptainFaqSuggestion struct {
	ID          int64
	Question    string
	Answer      string
	Embedding   interface{}
	AssistantID int64
	AccountID   int64
	Language    string
	SourceCount int32
	Status      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CaptainInbox struct {
	ID                 int64
	CaptainAssistantID int64
	InboxID            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type CaptainMessageReport struct {
	ID             int64
	AccountID      int64
	ConversationID int64
	MessageID      int64
	UserID         int64
	ReportReason   string
	Description    pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CaptainScenario struct {
	ID          int64
	Title       pgtype.Text
	Description pgtype.Text
	Instruction pgtype.Text
	Tools       []byte
	Enabled     bool
	AssistantID int64
	AccountID   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Category struct {
	ID                   int64
	AccountID            int32
	PortalID             int32
	Name                 pgtype.Text
	Description          pgtype.Text
	Position             pgtype.Int4
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Locale               pgtype.Text
	Slug                 string
	ParentCategoryID     pgtype.Int8
	AssociatedCategoryID pgtype.Int8
	Icon                 pgtype.Text
	IconColor            pgtype.Text
}

type ChannelApi struct {
	ID                   int64
	AccountID            int32
	WebhookUrl           pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Identifier           pgtype.Text
	HmacToken            pgtype.Text
	HmacMandatory        pgtype.Bool
	AdditionalAttributes []byte
	Secret               pgtype.Text
}

type ChannelEmail struct {
	ID                     int64
	AccountID              int32
	Email                  string
	ForwardToEmail         string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ImapEnabled            pgtype.Bool
	ImapAddress            pgtype.Text
	ImapPort               pgtype.Int4
	ImapLogin              pgtype.Text
	ImapPassword           pgtype.Text
	ImapEnableSsl          pgtype.Bool
	SmtpEnabled            pgtype.Bool
	SmtpAddress            pgtype.Text
	SmtpPort               pgtype.Int4
	SmtpLogin              pgtype.Text
	SmtpPassword           pgtype.Text
	SmtpDomain             pgtype.Text
	SmtpEnableStarttlsAuto pgtype.Bool
	SmtpAuthentication     pgtype.Text
	SmtpOpensslVerifyMode  pgtype.Text
	SmtpEnableSslTls       pgtype.Bool
	ProviderConfig         []byte
	Provider               pgtype.Text
	ImapAuthentication     pgtype.Text
	VerifiedForSending     bool
}

type ChannelFacebookPage struct {
	ID              int32
	PageID          string
	UserAccessToken string
	PageAccessToken string
	AccountID       int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	InstagramID     pgtype.Text
	ProviderName    pgtype.Text
}

type ChannelInstagram struct {
	ID           int64
	AccessToken  string
	ExpiresAt    time.Time
	AccountID    int32
	InstagramID  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ProviderName pgtype.Text
}

type ChannelLine struct {
	ID                int64
	AccountID         int32
	LineChannelID     string
	LineChannelSecret string
	LineChannelToken  string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ChannelSm struct {
	ID             int64
	AccountID      int32
	PhoneNumber    string
	Provider       pgtype.Text
	ProviderConfig []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ChannelTelegram struct {
	ID        int64
	BotName   pgtype.Text
	AccountID int32
	BotToken  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChannelTiktok struct {
	ID                    int64
	AccountID             int32
	BusinessID            string
	AccessToken           string
	ExpiresAt             time.Time
	RefreshToken          string
	RefreshTokenExpiresAt time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	ProviderName          pgtype.Text
}

type ChannelTwilioSm struct {
	ID                          int64
	PhoneNumber                 pgtype.Text
	AuthToken                   string
	AccountSid                  string
	AccountID                   int32
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	Medium                      pgtype.Int4
	MessagingServiceSid         pgtype.Text
	ApiKeySid                   pgtype.Text
	ContentTemplates            []byte
	ContentTemplatesLastUpdated *time.Time
	VoiceEnabled                bool
	TwimlAppSid                 pgtype.Text
	ApiKeySecret                pgtype.Text
	ProviderConfig              []byte
}

type ChannelTwitterProfile struct {
	ID                       int64
	ProfileID                string
	TwitterAccessToken       string
	TwitterAccessTokenSecret string
	AccountID                int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	TweetsEnabled            pgtype.Bool
}

type ChannelWebWidget struct {
	ID                 int32
	WebsiteUrl         pgtype.Text
	AccountID          pgtype.Int4
	CreatedAt          time.Time
	UpdatedAt          time.Time
	WebsiteToken       pgtype.Text
	WidgetColor        pgtype.Text
	WelcomeTitle       pgtype.Text
	WelcomeTagline     pgtype.Text
	FeatureFlags       int32
	ReplyTime          pgtype.Int4
	HmacToken          pgtype.Text
	PreChatFormEnabled pgtype.Bool
	PreChatFormOptions []byte
	HmacMandatory      pgtype.Bool
	ContinuityViaEmail bool
	AllowedDomains     pgtype.Text
}

type ChannelWhatsapp struct {
	ID                          int64
	AccountID                   int32
	BusinessManagementToken     pgtype.Text
	PhoneNumber                 string
	Provider                    pgtype.Text
	ProviderConfig              []byte
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	MessageTemplates            []byte
	MessageTemplatesLastUpdated *time.Time
	PhoneNumberHealth           []byte
	PhoneNumberHealthCheckedAt  *time.Time
	PhoneNumberHealthError      pgtype.Text
}

type ChatwooterAttachmentStorage struct {
	AttachmentID int32
	MessageID    int32
	Key          string
	Url          string
	ContentType  pgtype.Text
	SizeBytes    pgtype.Int4
	Metadata     []byte
}

type ChatwooterInboxConfig struct {
	InboxID        int32
	ProviderConfig []byte
}

type ChatwooterSession struct {
	ID        int64
	UserID    int32
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Company struct {
	ID                   int64
	Name                 string
	Domain               pgtype.Text
	Description          pgtype.Text
	AdditionalAttributes []byte
	AccountID            int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CustomAttributes     []byte
	ContactsCount        pgtype.Int4
	LastActivityAt       *time.Time
}

type Contact struct {
	ID                   int32
	AccountID            int32
	Name                 pgtype.Text
	PhoneNumber          pgtype.Text
	Email                pgtype.Text
	AdditionalAttributes []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CompanyID            pgtype.Int8
	Identifier           pgtype.Text
	CustomAttributes     []byte
	LastActivityAt       *time.Time
	ContactType          pgtype.Int4
	MiddleName           pgtype.Text
	LastName             pgtype.Text
	Location             pgtype.Text
	CountryCode          pgtype.Text
	Blocked              bool
}

type ContactInbox struct {
	ID           int64
	ContactID    pgtype.Int8
	InboxID      pgtype.Int8
	SourceID     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	HmacVerified pgtype.Bool
	PubsubToken  pgtype.Text
}

type Conversation struct {
	ID                   int32
	AccountID            int32
	InboxID              int32
	ContactInboxID       pgtype.Int8
	Status               int32
	LastActivityAt       time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AdditionalAttributes []byte
	AgentLastSeenAt      *time.Time
	AiAssigneeType       pgtype.Text
	AssigneeAgentBotID   pgtype.Int8
	AssigneeID           pgtype.Int4
	AssigneeLastSeenAt   *time.Time
	CachedLabelList      pgtype.Text
	CampaignID           pgtype.Int8
	ContactID            pgtype.Int8
	ContactLastSeenAt    *time.Time
	CustomAttributes     []byte
	DisplayID            int32
	FirstReplyCreatedAt  *time.Time
	Identifier           pgtype.Text
	Priority             pgtype.Int4
	SlaPolicyID          pgtype.Int8
	SnoozedUntil         *time.Time
	StatusChangedAt      *time.Time
	TeamID               pgtype.Int8
	Uuid                 pgtype.UUID
	WaitingSince         *time.Time
}

type ConversationMonitor struct {
	ID                 int64
	AccountID          int64
	UserID             pgtype.Int8
	Name               string
	Condition          string
	Model              string
	Threshold          float64
	HistorySince       time.Time
	PausedAt           *time.Time
	ResumedAt          *time.Time
	DeletedAt          *time.Time
	DataRevision       int64
	CollectionVersion  int64
	RecheckRequestedAt *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Icon               string
	IconColor          string
}

type ConversationMonitorDailyUsage struct {
	ID             int64
	AccountID      int64
	UsageDate      pgtype.Date
	CallsCount     int32
	LimitReachedAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConversationMonitorEvaluation struct {
	ID               int64
	AccountID        int64
	MonitorID        int64
	ConversationID   int64
	Status           string
	InputRevision    int64
	Generation       int64
	RequestedVersion pgtype.Int8
	Score            pgtype.Float8
	Model            pgtype.Text
	ErrorCode        pgtype.Text
	MatchedAt        *time.Time
	EvaluatedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ConversationMonitorScan struct {
	ID                int64
	MonitorID         int64
	Kind              string
	CollectionVersion int64
	StartedAt         time.Time
	EndedAt           time.Time
	Cursor            int64
	EnumeratedAt      *time.Time
	CancelledAt       *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ConversationMonitorWorkItem struct {
	ID                  int64
	AccountID           int64
	ConversationID      int64
	Revision            int64
	ProcessedRevision   int64
	FullHistoryRevision int64
	Generation          int64
	DueAt               *time.Time
	LeaseToken          pgtype.Text
	LeaseExpiresAt      *time.Time
	Attempts            int32
	ErrorCode           pgtype.Text
	RequestedAt         *time.Time
	ActivityAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ConversationOutcome struct {
	ID                    int64
	AccountID             int64
	AssistantID           int64
	ConversationID        int64
	InboxID               int64
	FirstCaptainReplyAt   *time.Time
	LastCaptainReplyAt    *time.Time
	CaptainReplyCount     int32
	FirstHumanReplyAt     *time.Time
	HandoffAt             *time.Time
	HandoffReasonCategory pgtype.Text
	ResolvedAt            *time.Time
	CsatRating            pgtype.Int4
	CsatReceivedAt        *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	EpisodeTrigger        string
	StartedAt             time.Time
	EndedAt               *time.Time
}

type ConversationParticipant struct {
	ID             int64
	AccountID      int64
	UserID         int64
	ConversationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CopilotMessage struct {
	ID              int64
	CopilotThreadID int64
	AccountID       int64
	Message         []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MessageType     pgtype.Int4
}

type CopilotThread struct {
	ID          int64
	Title       string
	UserID      int64
	AccountID   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AssistantID pgtype.Int4
}

type CsatSurveyResponse struct {
	ID                     int64
	AccountID              int64
	ConversationID         int64
	MessageID              int64
	Rating                 int32
	FeedbackMessage        pgtype.Text
	ContactID              int64
	AssignedAgentID        pgtype.Int8
	CreatedAt              time.Time
	UpdatedAt              time.Time
	CsatReviewNotes        pgtype.Text
	ReviewNotesUpdatedAt   *time.Time
	ReviewNotesUpdatedByID pgtype.Int8
}

type CustomAttributeDefinition struct {
	ID                   int64
	AttributeDisplayName pgtype.Text
	AttributeKey         pgtype.Text
	AttributeDisplayType pgtype.Int4
	DefaultValue         pgtype.Int4
	AttributeModel       pgtype.Int4
	AccountID            pgtype.Int8
	AttributeDescription pgtype.Text
	AttributeValues      []byte
	RegexPattern         pgtype.Text
	RegexCue             pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type CustomFilter struct {
	ID         int64
	Name       string
	FilterType int32
	Query      []byte
	AccountID  int64
	UserID     int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CustomRole struct {
	ID          int64
	Name        pgtype.Text
	Description pgtype.Text
	AccountID   int64
	Permissions []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DashboardApp struct {
	ID        int64
	Title     string
	Content   []byte
	AccountID int64
	UserID    pgtype.Int8
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DataImport struct {
	ID               int64
	AccountID        int64
	DataType         string
	Status           int32
	ProcessingErrors pgtype.Text
	TotalRecords     pgtype.Int4
	ProcessedRecords pgtype.Int4
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             pgtype.Text
	SourceType       pgtype.Text
	SourceProvider   pgtype.Text
	ImportTypes      []byte
	InitiatedByID    pgtype.Int4
	AccessToken      pgtype.Text
	SourceMetadata   []byte
	Stats            []byte
	Cursor           []byte
	StartedAt        *time.Time
	CompletedAt      *time.Time
	AbandonedAt      *time.Time
	LastErrorAt      *time.Time
}

type DataImportError struct {
	ID               int64
	DataImportID     int64
	DataImportItemID pgtype.Int8
	SourceObjectType pgtype.Text
	SourceObjectID   pgtype.Text
	ErrorCode        string
	Message          pgtype.Text
	Details          []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type DataImportItem struct {
	ID                 int64
	DataImportID       int64
	SourceProvider     string
	SourceObjectType   string
	SourceObjectID     string
	Status             int32
	ChatwootRecordType pgtype.Text
	ChatwootRecordID   pgtype.Int8
	AttemptCount       int32
	LastErrorCode      pgtype.Text
	LastErrorMessage   pgtype.Text
	Metadata           []byte
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type DataImportMapping struct {
	ID                 int64
	AccountID          int32
	DataImportID       int64
	SourceProvider     string
	SourceObjectType   string
	SourceObjectID     string
	ChatwootRecordType string
	ChatwootRecordID   int64
	Metadata           []byte
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type EmailTemplate struct {
	ID           int64
	Name         string
	Body         string
	AccountID    pgtype.Int4
	TemplateType pgtype.Int4
	Locale       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	InboxID      pgtype.Int4
}

type Folder struct {
	ID         int64
	AccountID  int32
	CategoryID int32
	Name       pgtype.Text
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ImportError struct {
	ID          int64
	ImportRunID int64
	SourceTable string
	SourceID    int64
	Code        string
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type ImportMapping struct {
	ID          int64
	AccountID   int64
	SourceTable string
	OldID       int64
	NewID       int64
	InsertedAt  time.Time
	UpdatedAt   time.Time
}

type ImportRun struct {
	ID              int64
	AccountID       int64
	SourceAccountID int64
	Status          string
	Attempts        int32
	ProcessedCount  int32
	FailedCount     int32
	InsertedAt      time.Time
	UpdatedAt       time.Time
}

type Inbox struct {
	ID                         int32
	AccountID                  int32
	Name                       string
	ChannelType                pgtype.Text
	GreetingMessage            pgtype.Text
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	PortalID                   pgtype.Int8
	ChannelID                  int32
	AllowMessagesAfterResolved pgtype.Bool
	AutoAssignmentConfig       []byte
	BusinessName               pgtype.Text
	CsatConfig                 []byte
	CsatSurveyEnabled          pgtype.Bool
	EmailAddress               pgtype.Text
	EnableAutoAssignment       pgtype.Bool
	EnableEmailCollect         pgtype.Bool
	GreetingEnabled            pgtype.Bool
	LockToSingleConversation   bool
	OutOfOfficeMessage         pgtype.Text
	SenderNameType             int32
	Timezone                   pgtype.Text
	WorkingHoursEnabled        pgtype.Bool
}

type InboxAssignmentPolicy struct {
	ID                 int64
	InboxID            int64
	AssignmentPolicyID int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InboxCapacityLimit struct {
	ID                    int64
	AgentCapacityPolicyID int64
	InboxID               int64
	ConversationLimit     int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type InboxMember struct {
	ID        int32
	InboxID   int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type InstallationConfig struct {
	ID              int64
	Name            string
	SerializedValue []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Locked          bool
}

type IntegrationsHook struct {
	ID          int64
	Status      pgtype.Int4
	InboxID     pgtype.Int4
	AccountID   pgtype.Int4
	AppID       pgtype.Text
	HookType    pgtype.Int4
	ReferenceID pgtype.Text
	AccessToken pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Settings    []byte
}

type Label struct {
	ID            int64
	Title         pgtype.Text
	Description   pgtype.Text
	Color         string
	ShowOnSidebar pgtype.Bool
	AccountID     pgtype.Int8
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Leafe struct {
	ID           int64
	AccountID    int64
	UserID       int64
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	LeaveType    int32
	Status       int32
	Reason       pgtype.Text
	ApprovedByID pgtype.Int8
	ApprovedAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Macro struct {
	ID          int64
	AccountID   int64
	Name        string
	Visibility  pgtype.Int4
	CreatedByID pgtype.Int8
	UpdatedByID pgtype.Int8
	Actions     []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Mention struct {
	ID             int64
	UserID         int64
	ConversationID int64
	AccountID      int64
	MentionedAt    time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Message struct {
	ID                      int32
	ConversationID          int32
	AccountID               int32
	InboxID                 int32
	SenderID                pgtype.Int8
	MessageType             int32
	Content                 pgtype.Text
	Private                 bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
	SourceID                pgtype.Text
	ContentType             int32
	Status                  pgtype.Int4
	AdditionalAttributes    []byte
	ContentAttributes       []byte
	ExternalSourceIds       []byte
	ProcessedMessageContent pgtype.Text
	SenderType              pgtype.Text
	Sentiment               []byte
}

type Note struct {
	ID        int64
	Content   string
	AccountID int64
	ContactID int64
	UserID    pgtype.Int8
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Notification struct {
	ID                 int64
	AccountID          int64
	UserID             int64
	NotificationType   int32
	PrimaryActorType   string
	PrimaryActorID     int64
	SecondaryActorType pgtype.Text
	SecondaryActorID   pgtype.Int8
	ReadAt             *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SnoozedUntil       *time.Time
	LastActivityAt     *time.Time
	Meta               []byte
}

type NotificationSetting struct {
	ID         int64
	AccountID  pgtype.Int4
	UserID     pgtype.Int4
	EmailFlags int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PushFlags  int32
}

type NotificationSubscription struct {
	ID                     int64
	UserID                 int64
	SubscriptionType       int32
	SubscriptionAttributes []byte
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Identifier             pgtype.Text
}

type PlatformApp struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlatformAppPermissible struct {
	ID              int64
	PlatformAppID   int64
	PermissibleType string
	PermissibleID   int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlatformBanner struct {
	ID            int64
	BannerMessage string
	BannerType    int32
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Portal struct {
	ID                 int64
	AccountID          int32
	Name               string
	Slug               string
	CustomDomain       pgtype.Text
	Color              pgtype.Text
	HomepageLink       pgtype.Text
	PageTitle          pgtype.Text
	HeaderText         pgtype.Text
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Config             []byte
	Archived           pgtype.Bool
	ChannelWebWidgetID pgtype.Int8
	SslSettings        []byte
}

type PortalsMember struct {
	PortalID int64
	UserID   int64
}

type RelatedCategory struct {
	ID                int64
	CategoryID        pgtype.Int8
	RelatedCategoryID pgtype.Int8
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ReportingEvent struct {
	ID                   int64
	Name                 pgtype.Text
	Value                pgtype.Float8
	AccountID            pgtype.Int4
	InboxID              pgtype.Int4
	UserID               pgtype.Int4
	ConversationID       pgtype.Int4
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ValueInBusinessHours pgtype.Float8
	EventStartTime       *time.Time
	EventEndTime         *time.Time
}

type ReportingEventsRollup struct {
	ID                    int64
	AccountID             int32
	Date                  pgtype.Date
	DimensionType         string
	DimensionID           int64
	Metric                string
	Count                 int64
	SumValue              float64
	SumValueBusinessHours float64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type SlaEvent struct {
	ID             int64
	AppliedSlaID   int64
	ConversationID int64
	AccountID      int64
	SlaPolicyID    int64
	InboxID        int64
	EventType      pgtype.Int4
	Meta           []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SlaPolicy struct {
	ID                         int64
	Name                       string
	FirstResponseTimeThreshold pgtype.Float8
	NextResponseTimeThreshold  pgtype.Float8
	OnlyDuringBusinessHours    pgtype.Bool
	AccountID                  int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	Description                pgtype.Text
	ResolutionTimeThreshold    pgtype.Float8
}

type Tag struct {
	ID            int32
	Name          pgtype.Text
	TaggingsCount pgtype.Int4
}

type Tagging struct {
	ID           int32
	TagID        pgtype.Int4
	TaggableType pgtype.Text
	TaggableID   pgtype.Int4
	TaggerType   pgtype.Text
	TaggerID     pgtype.Int4
	Context      pgtype.Text
	CreatedAt    *time.Time
}

type Team struct {
	ID              int64
	AccountID       int64
	Name            string
	Description     pgtype.Text
	AllowAutoAssign pgtype.Bool
	Icon            pgtype.Text
	IconColor       pgtype.Text
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TeamMember struct {
	ID        int64
	TeamID    int64
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                  int32
	Email               pgtype.Text
	EncryptedPassword   string
	ConfirmedAt         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Name                string
	LastSignInAt        *time.Time
	CurrentSignInAt     *time.Time
	ResetPasswordSentAt *time.Time
	SignInCount         int32
	ResetPasswordToken  pgtype.Text
	Uid                 string
	OtpRequiredForLogin pgtype.Bool
	DisplayName         pgtype.Text
	ConsumedTimestep    pgtype.Int4
	CurrentSignInIp     pgtype.Text
	Type                pgtype.Text
	CustomAttributes    []byte
	LastSignInIp        pgtype.Text
	PubsubToken         pgtype.Text
	Tokens              []byte
	Availability        pgtype.Int4
	OtpBackupCodes      pgtype.Text
	OtpSecret           pgtype.Text
	ConfirmationSentAt  *time.Time
	DeviceTrustVersion  int32
	UiSettings          []byte
	ConfirmationToken   pgtype.Text
	MessageSignature    pgtype.Text
	RememberCreatedAt   *time.Time
	UnconfirmedEmail    pgtype.Text
	Provider            string
}

type UserSession struct {
	ID              int64
	UserID          int64
	ClientID        string
	IpAddress       pgtype.Text
	UserAgent       pgtype.Text
	BrowserName     pgtype.Text
	BrowserVersion  pgtype.Text
	DeviceName      pgtype.Text
	PlatformName    pgtype.Text
	PlatformVersion pgtype.Text
	City            pgtype.Text
	Country         pgtype.Text
	CountryCode     pgtype.Text
	LastActivityAt  *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Webhook struct {
	ID            int64
	AccountID     pgtype.Int4
	InboxID       pgtype.Int4
	Url           pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
	WebhookType   pgtype.Int4
	Subscriptions []byte
	Name          pgtype.Text
	Secret        pgtype.Text
}

type WorkingHour struct {
	ID           int64
	InboxID      pgtype.Int8
	AccountID    pgtype.Int8
	DayOfWeek    int32
	ClosedAllDay pgtype.Bool
	OpenHour     pgtype.Int4
	OpenMinutes  pgtype.Int4
	CloseHour    pgtype.Int4
	CloseMinutes pgtype.Int4
	OpenAllDay   pgtype.Bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
