// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM chatwooter_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.encrypted_password, u.confirmed_at, u.created_at, u.updated_at, u.name, u.last_sign_in_at, u.current_sign_in_at, u.reset_password_sent_at, u.sign_in_count, u.reset_password_token, u.uid, u.otp_required_for_login, u.display_name, u.consumed_timestep, u.current_sign_in_ip, u.type, u.custom_attributes, u.last_sign_in_ip, u.pubsub_token, u.tokens, u.availability, u.otp_backup_codes, u.otp_secret, u.confirmation_sent_at, u.device_trust_version, u.ui_settings, u.confirmation_token, u.message_signature, u.remember_created_at, u.unconfirmed_email, u.provider
FROM chatwooter_sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > (now() AT TIME ZONE 'utc')
`

type GetSessionUserRow struct {
	User User
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.EncryptedPassword,
		&i.User.ConfirmedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Name,
		&i.User.LastSignInAt,
		&i.User.CurrentSignInAt,
		&i.User.ResetPasswordSentAt,
		&i.User.SignInCount,
		&i.User.ResetPasswordToken,
		&i.User.Uid,
		&i.User.OtpRequiredForLogin,
		&i.User.DisplayName,
		&i.User.ConsumedTimestep,
		&i.User.CurrentSignInIp,
		&i.User.Type,
		&i.User.CustomAttributes,
		&i.User.LastSignInIp,
		&i.User.PubsubToken,
		&i.User.Tokens,
		&i.User.Availability,
		&i.User.OtpBackupCodes,
		&i.User.OtpSecret,
		&i.User.ConfirmationSentAt,
		&i.User.DeviceTrustVersion,
		&i.User.UiSettings,
		&i.User.ConfirmationToken,
		&i.User.MessageSignature,
		&i.User.RememberCreatedAt,
		&i.User.UnconfirmedEmail,
		&i.User.Provider,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO chatwooter_sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	UserID    int32
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM chatwooter_sessions WHERE expires_at <= (now() AT TIME ZONE 'utc')
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
