// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, t.description, t.allow_auto_assign, t.icon, t.icon_color, t.account_id,
       EXISTS (SELECT 1 FROM team_members tm WHERE tm.team_id = t.id AND tm.user_id = $1) AS is_member
FROM teams t WHERE t.account_id = $2 ORDER BY t.id
`

type ListTeamsParams struct {
	UserID    int64
	AccountID int64
}

type ListTeamsRow struct {
	ID              int64
	Name            string
	Description     pgtype.Text
	AllowAutoAssign pgtype.Bool
	Icon            pgtype.Text
	IconColor       pgtype.Text
	AccountID       int64
	IsMember        bool
}

// is_member: o usuário da sessão está no time (_team.json.jbuilder).
func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AllowAutoAssign,
			&i.Icon,
			&i.IconColor,
			&i.AccountID,
			&i.IsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
