// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMembership = `-- name: GetMembership :one
SELECT au.account_id, a.name AS account_name, a.status AS account_status,
       a.custom_attributes AS account_custom_attributes,
       au.active_at, au.role, au.availability, au.auto_offline, au.inviter_id
FROM account_users au JOIN accounts a ON a.id = au.account_id
WHERE au.user_id = $1 AND au.account_id = $2
`

type GetMembershipParams struct {
	UserID    pgtype.Int8
	AccountID pgtype.Int8
}

type GetMembershipRow struct {
	AccountID               pgtype.Int8
	AccountName             string
	AccountStatus           pgtype.Int4
	AccountCustomAttributes []byte
	ActiveAt                *time.Time
	Role                    pgtype.Int4
	Availability            int32
	AutoOffline             bool
	InviterID               pgtype.Int8
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.AccountID)
	var i GetMembershipRow
	err := row.Scan(
		&i.AccountID,
		&i.AccountName,
		&i.AccountStatus,
		&i.AccountCustomAttributes,
		&i.ActiveAt,
		&i.Role,
		&i.Availability,
		&i.AutoOffline,
		&i.InviterID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, encrypted_password, confirmed_at, created_at, updated_at, name, last_sign_in_at, current_sign_in_at, reset_password_sent_at, sign_in_count, reset_password_token, uid, otp_required_for_login, display_name, consumed_timestep, current_sign_in_ip, type, custom_attributes, last_sign_in_ip, pubsub_token, tokens, availability, otp_backup_codes, otp_secret, confirmation_sent_at, device_trust_version, ui_settings, confirmation_token, message_signature, remember_created_at, unconfirmed_email, provider FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EncryptedPassword,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.LastSignInAt,
		&i.CurrentSignInAt,
		&i.ResetPasswordSentAt,
		&i.SignInCount,
		&i.ResetPasswordToken,
		&i.Uid,
		&i.OtpRequiredForLogin,
		&i.DisplayName,
		&i.ConsumedTimestep,
		&i.CurrentSignInIp,
		&i.Type,
		&i.CustomAttributes,
		&i.LastSignInIp,
		&i.PubsubToken,
		&i.Tokens,
		&i.Availability,
		&i.OtpBackupCodes,
		&i.OtpSecret,
		&i.ConfirmationSentAt,
		&i.DeviceTrustVersion,
		&i.UiSettings,
		&i.ConfirmationToken,
		&i.MessageSignature,
		&i.RememberCreatedAt,
		&i.UnconfirmedEmail,
		&i.Provider,
	)
	return i, err
}

const getUserAccessToken = `-- name: GetUserAccessToken :one
SELECT token FROM access_tokens WHERE owner_type = 'User' AND owner_id = $1 ORDER BY id LIMIT 1
`

func (q *Queries) GetUserAccessToken(ctx context.Context, ownerID pgtype.Int8) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserAccessToken, ownerID)
	var token pgtype.Text
	err := row.Scan(&token)
	return token, err
}

const getUserByAccessToken = `-- name: GetUserByAccessToken :one
SELECT u.id, u.email, u.encrypted_password, u.confirmed_at, u.created_at, u.updated_at, u.name, u.last_sign_in_at, u.current_sign_in_at, u.reset_password_sent_at, u.sign_in_count, u.reset_password_token, u.uid, u.otp_required_for_login, u.display_name, u.consumed_timestep, u.current_sign_in_ip, u.type, u.custom_attributes, u.last_sign_in_ip, u.pubsub_token, u.tokens, u.availability, u.otp_backup_codes, u.otp_secret, u.confirmation_sent_at, u.device_trust_version, u.ui_settings, u.confirmation_token, u.message_signature, u.remember_created_at, u.unconfirmed_email, u.provider
FROM users u JOIN access_tokens t ON t.owner_id = u.id AND t.owner_type = 'User'
WHERE t.token = $1
`

type GetUserByAccessTokenRow struct {
	User User
}

func (q *Queries) GetUserByAccessToken(ctx context.Context, token pgtype.Text) (GetUserByAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByAccessToken, token)
	var i GetUserByAccessTokenRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.EncryptedPassword,
		&i.User.ConfirmedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Name,
		&i.User.LastSignInAt,
		&i.User.CurrentSignInAt,
		&i.User.ResetPasswordSentAt,
		&i.User.SignInCount,
		&i.User.ResetPasswordToken,
		&i.User.Uid,
		&i.User.OtpRequiredForLogin,
		&i.User.DisplayName,
		&i.User.ConsumedTimestep,
		&i.User.CurrentSignInIp,
		&i.User.Type,
		&i.User.CustomAttributes,
		&i.User.LastSignInIp,
		&i.User.PubsubToken,
		&i.User.Tokens,
		&i.User.Availability,
		&i.User.OtpBackupCodes,
		&i.User.OtpSecret,
		&i.User.ConfirmationSentAt,
		&i.User.DeviceTrustVersion,
		&i.User.UiSettings,
		&i.User.ConfirmationToken,
		&i.User.MessageSignature,
		&i.User.RememberCreatedAt,
		&i.User.UnconfirmedEmail,
		&i.User.Provider,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT au.account_id, a.name AS account_name, a.status AS account_status,
       a.custom_attributes AS account_custom_attributes,
       au.active_at, au.role, au.availability, au.auto_offline, au.inviter_id
FROM account_users au JOIN accounts a ON a.id = au.account_id
WHERE au.user_id = $1
ORDER BY au.account_id
`

type ListMembershipsRow struct {
	AccountID               pgtype.Int8
	AccountName             string
	AccountStatus           pgtype.Int4
	AccountCustomAttributes []byte
	ActiveAt                *time.Time
	Role                    pgtype.Int4
	Availability            int32
	AutoOffline             bool
	InviterID               pgtype.Int8
}

func (q *Queries) ListMemberships(ctx context.Context, userID pgtype.Int8) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.AccountStatus,
			&i.AccountCustomAttributes,
			&i.ActiveAt,
			&i.Role,
			&i.Availability,
			&i.AutoOffline,
			&i.InviterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByEmail = `-- name: UsersByEmail :many
SELECT id, email, encrypted_password, confirmed_at, created_at, updated_at, name, last_sign_in_at, current_sign_in_at, reset_password_sent_at, sign_in_count, reset_password_token, uid, otp_required_for_login, display_name, consumed_timestep, current_sign_in_ip, type, custom_attributes, last_sign_in_ip, pubsub_token, tokens, availability, otp_backup_codes, otp_secret, confirmation_sent_at, device_trust_version, ui_settings, confirmation_token, message_signature, remember_created_at, unconfirmed_email, provider FROM users WHERE lower(email) = lower($1) LIMIT 2
`

// Até 2 linhas: basta para detectar e-mail ambíguo em dumps restaurados.
func (q *Queries) UsersByEmail(ctx context.Context, lower string) ([]User, error) {
	rows, err := q.db.Query(ctx, usersByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EncryptedPassword,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.LastSignInAt,
			&i.CurrentSignInAt,
			&i.ResetPasswordSentAt,
			&i.SignInCount,
			&i.ResetPasswordToken,
			&i.Uid,
			&i.OtpRequiredForLogin,
			&i.DisplayName,
			&i.ConsumedTimestep,
			&i.CurrentSignInIp,
			&i.Type,
			&i.CustomAttributes,
			&i.LastSignInIp,
			&i.PubsubToken,
			&i.Tokens,
			&i.Availability,
			&i.OtpBackupCodes,
			&i.OtpSecret,
			&i.ConfirmationSentAt,
			&i.DeviceTrustVersion,
			&i.UiSettings,
			&i.ConfirmationToken,
			&i.MessageSignature,
			&i.RememberCreatedAt,
			&i.UnconfirmedEmail,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
