/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppAuthenticatedConversationsRouteImport } from './routes/app/_authenticated/_conversations'
import { Route as AppAuthenticatedConversationsIndexRouteImport } from './routes/app/_authenticated/_conversations/index'
import { Route as AppAuthenticatedContactsIndexRouteImport } from './routes/app/_authenticated/contacts/index'
import { Route as AppAuthenticatedContactsContactIdRouteImport } from './routes/app/_authenticated/contacts/$contactId'
import { Route as AppAuthenticatedConversationsConversationsConversationIdRouteImport } from './routes/app/_authenticated/_conversations/conversations.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedConversationsRoute =
  AppAuthenticatedConversationsRouteImport.update({
    id: '/_conversations',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedConversationsIndexRoute =
  AppAuthenticatedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedConversationsRoute,
  } as any)
const AppAuthenticatedContactsIndexRoute =
  AppAuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedContactsContactIdRoute =
  AppAuthenticatedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedConversationsConversationsConversationIdRoute =
  AppAuthenticatedConversationsConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AppAuthenticatedConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedConversationsRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/contacts/$contactId': typeof AppAuthenticatedContactsContactIdRoute
  '/app/': typeof AppAuthenticatedConversationsIndexRoute
  '/app/contacts/': typeof AppAuthenticatedContactsIndexRoute
  '/app/conversations/$conversationId': typeof AppAuthenticatedConversationsConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedConversationsIndexRoute
  '/app/login': typeof AppLoginRoute
  '/app/contacts/$contactId': typeof AppAuthenticatedContactsContactIdRoute
  '/app/contacts': typeof AppAuthenticatedContactsIndexRoute
  '/app/conversations/$conversationId': typeof AppAuthenticatedConversationsConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/_authenticated/_conversations': typeof AppAuthenticatedConversationsRouteWithChildren
  '/app/_authenticated/contacts/$contactId': typeof AppAuthenticatedContactsContactIdRoute
  '/app/_authenticated/_conversations/': typeof AppAuthenticatedConversationsIndexRoute
  '/app/_authenticated/contacts/': typeof AppAuthenticatedContactsIndexRoute
  '/app/_authenticated/_conversations/conversations/$conversationId': typeof AppAuthenticatedConversationsConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/login'
    | '/app/contacts/$contactId'
    | '/app/'
    | '/app/contacts/'
    | '/app/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/login'
    | '/app/contacts/$contactId'
    | '/app/contacts'
    | '/app/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/app/_authenticated'
    | '/app/login'
    | '/app/_authenticated/_conversations'
    | '/app/_authenticated/contacts/$contactId'
    | '/app/_authenticated/_conversations/'
    | '/app/_authenticated/contacts/'
    | '/app/_authenticated/_conversations/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/_conversations': {
      id: '/app/_authenticated/_conversations'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedConversationsRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/_conversations/': {
      id: '/app/_authenticated/_conversations/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AppAuthenticatedConversationsRoute
    }
    '/app/_authenticated/contacts/': {
      id: '/app/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppAuthenticatedContactsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/contacts/$contactId': {
      id: '/app/_authenticated/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/app/contacts/$contactId'
      preLoaderRoute: typeof AppAuthenticatedContactsContactIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/_conversations/conversations/$conversationId': {
      id: '/app/_authenticated/_conversations/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/app/conversations/$conversationId'
      preLoaderRoute: typeof AppAuthenticatedConversationsConversationsConversationIdRouteImport
      parentRoute: typeof AppAuthenticatedConversationsRoute
    }
  }
}

interface AppAuthenticatedConversationsRouteChildren {
  AppAuthenticatedConversationsIndexRoute: typeof AppAuthenticatedConversationsIndexRoute
  AppAuthenticatedConversationsConversationsConversationIdRoute: typeof AppAuthenticatedConversationsConversationsConversationIdRoute
}

const AppAuthenticatedConversationsRouteChildren: AppAuthenticatedConversationsRouteChildren =
  {
    AppAuthenticatedConversationsIndexRoute:
      AppAuthenticatedConversationsIndexRoute,
    AppAuthenticatedConversationsConversationsConversationIdRoute:
      AppAuthenticatedConversationsConversationsConversationIdRoute,
  }

const AppAuthenticatedConversationsRouteWithChildren =
  AppAuthenticatedConversationsRoute._addFileChildren(
    AppAuthenticatedConversationsRouteChildren,
  )

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedConversationsRoute: typeof AppAuthenticatedConversationsRouteWithChildren
  AppAuthenticatedContactsContactIdRoute: typeof AppAuthenticatedContactsContactIdRoute
  AppAuthenticatedContactsIndexRoute: typeof AppAuthenticatedContactsIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedConversationsRoute:
    AppAuthenticatedConversationsRouteWithChildren,
  AppAuthenticatedContactsContactIdRoute:
    AppAuthenticatedContactsContactIdRoute,
  AppAuthenticatedContactsIndexRoute: AppAuthenticatedContactsIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
